Repaso_2EV/Controllers/MarcaController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Repaso_2EV.Models;

namespace Repaso_2EV.Controllers
{
    public class MarcaController : Controller
    {

        public Contexto Contexto { get; }

        public MarcaController(Contexto contexto)
        {
            Contexto = contexto;
        }
        // GET: MarcaController1
        public ActionResult Index()
        {
            var lista = Contexto.Marcas.ToList();
            return View(lista);
        }

        public ActionResult Listado()
        {
            List<MarcaModelo> lista = Contexto.Marcas.Include("Series").ToList();
            return View(lista);
        }

        public ActionResult Desplegable()
        {
            ViewBag.Marcas = new SelectList(Contexto.Marcas, "Id", "Nom_Marca");
            ViewBag.Marcas2 = Contexto.Marcas.ToList();
            return View();
        }

        // GET: MarcaController1/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: MarcaController1/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: MarcaController1/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(MarcaModelo marca)
        {
            try
            {

                Contexto.Marcas.Add(marca);
                Contexto.Database.EnsureCreated();
                Contexto.SaveChanges();
                return View("Create");
            }
            catch
            {
                return View("Create");
            }
        }

        // GET: MarcaController1/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: MarcaController1/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: MarcaController1/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: MarcaController1/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Repaso_2EV/Controllers/SerieController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Repaso_2EV.Models;

namespace Repaso_2EV.Controllers
{
    public class SerieController : Controller
    {
        Contexto Contexto { get; set; }

        public SerieController(Contexto contexto)
        {
            Contexto = contexto;
        }
        // GET: SerieController
        public ActionResult Index()
        {
            var lista = Contexto.Series.Include(s => s.Marca).ToList();
            return View(lista);
        }

        public ActionResult Listado(int id)
        {
            List<SerieModelo> lista = this.Contexto.Series.Include("Marca").ToList();
            // Encuentra el índice del elemento con el ID especificado
            List<SerieModelo> listaMarca = lista.FindAll(item => item.MarcaID == id);
            // List<SerieModelo> listaMarca = lista.FindAll(item => item.MarcaId == id);
            if (id > 0)
            {
                // Si se encontró, pasa el elemento correspondiente a la vista
                return View(listaMarca);
            }
            else
            {
                return RedirectToAction("Error");
            }
        }

        // GET: SerieController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: SerieController/Create
        public ActionResult Create()
        {
            ViewBag.MarcaID = new SelectList(Contexto.Marcas, "Id", "Nom_Marca");
            return View();
        }

        // POST: SerieController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(SerieModelo serie)
        {
            try
            {
                Contexto.Series.Add(serie);
                Contexto.SaveChanges();

                return View("Create");
            }
            catch
            {
                return View("Create");
            }
        }

        // GET: SerieController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: SerieController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: SerieController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: SerieController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Repaso_2EV/Views/Marca/Create.cshtml
@model Repaso_2EV.Models.MarcaModelo

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>MarcaModelo</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nom_Marca" class="control-label">Nom_Marca</label>
                <input asp-for="Nom_Marca" class="form-control" />
                <span asp-validation-for="Nom_Marca" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Repaso_2EV/Views/Marca/Desplegable.cshtml
@{
    ViewData["Title"] = "Desplegable";
}

<h1>Desplegable</h1>

@Html.DropDownList("LasMarcas", new List<SelectListItem>
{
    new SelectListItem{Text="Opel",Value="1",Selected=true},
    new SelectListItem{Text="Ferrari",Value="2",},
    new SelectListItem{Text="Mercedes",Value="3",}

},"Selecciona una marca")


@Html.DropDownList("Marcas","Selecciona una marca")


<select id="Marcos" name="Marcos">
    @foreach (MarcaModelo marca in ViewBag.Marcas2)
    {
        <option value=@marca.Id>@marca.Nom_Marca</option>
        
    }
</select>

Repaso_2EV/Views/Marca/Index.cshtml
@model IEnumerable<Repaso_2EV.Models.MarcaModelo>

@{
	ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<p>
    <a asp-action="Listado">Listado</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayName("Marca")  
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Nom_Marca)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

Repaso_2EV/Views/Marca/Listado.cshtml
@model IEnumerable<Repaso_2EV.Models.MarcaModelo>

@{
    ViewData["Title"] = "Listado";
}

<h1>Listado</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th></th>
            <th>
                @Html.DisplayNameFor(model => model.Nom_Marca)
            </th>
            <th>
                @Html.DisplayName("Marcas Metodo de Agustin")
            </th>
            <th>Opciones de Modificación</th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td></td>
            <td>
                    <a asp-action="Listado" asp-controller="Serie" asp-route-id="@item.Id">@item.Nom_Marca</a>
                    @* ChatGPT *@
                    @* @Html.ActionLink(Html.DisplayFor(modelItem => item.NomMarca).ToString(), "Details", new { id = item.Id }) *@

            </td>
                <td>
                    <a asp-action="ListadoAgustin" asp-controller="Serie" asp-route-id="@item.Id">@item.Nom_Marca</a>
                </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>